---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "environments"
  labels:
    nirmata.io/deployment.name: "environments"
    nirmata.io/service.name: "environments"
    nirmata.io/type: "app"
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      nirmata.io/service.name: "environments"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        nirmata.io/deployment.name: "environments"
        nirmata.io/service.name: "environments"
        nirmata.io/type: "app"
        nirmata.io/force.rolling.update: "4"
    spec:
      serviceAccountName: "environments-service"
      automountServiceAccountToken: false
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      schedulerName: "default-scheduler"
      priorityClassName: "nirmata-app-critical"
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: registry-v2.nirmata.io
      - name: ghcr.io
      containers:
      - name: "environments"
        image: "ghcr.io/nirmata/environments:4.20.0-3.g6b895a0"
        command: []
        args: []
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: "File"
        imagePullPolicy: "Always"
        ports:
        - name: "yourkit"
          containerPort: 10001
          protocol: "TCP"
        - name: "https"
          containerPort: 8443
          protocol: "TCP"
        - name: "jmx"
          containerPort: 8080
          protocol: "HTTP"
        env:
        - name: "nirmata.environments-processor"
          value: "false"
        - name: "nirmata.timeseries.readpreference"
          value: "secondary"
        - name: "nirmata.mongodb.readpreference.nearest"
          value: "Alarm,AlarmType"
        - name: "JAVA_TOOL_OPTIONS"
          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 \
        -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENTITY_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: "service.es.address"
          value: "elasticsearch"
        - name: "JAVA_OPTS"
          value: "-XshowSettings:vm  -XX:MaxRAMPercentage=70.0 -agentpath:/usr/local/YourKit-JavaProfiler-2023.5/bin/linux-musl-x86-64/libyjpagent.so=port=10001,listen=all"
        - name: "nirmata.environment.name"
          valueFrom:
            fieldRef:
              apiVersion: "v1"
              fieldPath: "metadata.namespace"
        - name: "eureka.registration.enabled"
          value: "false"
        - name: "nirmata.service.dnsclient"
          value: "true"
        - name: "nirmata.locks.mongo.enabled"
          value: "true"
        - name: "service.mongodb.seedSet"
          value: "mongodb:27017"
        - name: "nirmata.zookeeper.address"
          value: "zookeeper:2181"
        - name: "nirmata.kafka.address"
          value: "kafka:9092"
        - name: "service.logs.level"
          value: "warn"
        - name: "nirmata.workflow.usecurator"
          value: "false"
        - name: "nirmata.alarms.curatorforworkflow"
          value: "false"
        - name: nirmata.gateway.address
          valueFrom:
            configMapKeyRef:
              key: nirmata.url
              name: nirmata-config
        - name: "nirmata.tunnelServer.address"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "tunnelServerAddress"
        - name: "HTTP_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "HTTP_PROXY"
        - name: "HTTPS_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "HTTPS_PROXY"
        - name: "NO_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "NO_PROXY"
        - name: "http_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "http_proxy"
        - name: "https_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "https_proxy"
        - name: "no_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "no_proxy"
        livenessProbe:
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: "/environments/status"
            port: 8443
            scheme: "HTTPS"
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: "/environments/status"
            port: 8443
            scheme: "HTTPS"
        resources:
          limits:
            memory: "6Gi"
          requests:
            memory: "6Gi"
            cpu: 2
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        supplementalGroups: []
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-west-2a
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: nirmata.io/deployment.name
                  operator: In
                  values:
                  - cluster
                  - environments
              topologyKey: topology.kubernetes.io/hostname
            weight: 1              
      tolerations:      
      - key: "nirmata.io/dedicated-worker-group"
        operator: "Equal"
        value: "worker-group-1"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
